skeddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
end

skeddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

skeddit/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, :moderator_id, presence: true
  validates :moderator_id, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User
end

skeddit/app/models/user.rb
#FIG VAPER
##########
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password) 
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password) 
  end

  def reset_session_token!
    #
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  

end

skeddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :logged_in?, :current_user
  # CELLL ME
  def current_user
    #
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_logged_in
    #
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    #
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

end

skeddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login!(@user)
      redirect_to users_url
    else
      flash.now[errors] = ["Invalid Input"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end

end

skeddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to subs_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(sub_params)

    if sub.update
      redirect_to subs_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end
end

skeddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(parmams[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

skeddit/app/helpers/application_helper.rb
module ApplicationHelper
end

skeddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

skeddit/app/helpers/subs_helper.rb
module SubsHelper
end

skeddit/app/helpers/users_helper.rb
module UsersHelper
end

skeddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skeddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Lizz0LogOut">
      </form>
    <% end %>
  </body>
</html>

skeddit/app/views/subs/edit.html.erb
<h1>Edit Sub-topic</h1>

skeddit/app/views/subs/new.html.erb
<h1>Create Sub-topic</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="sub[title]">
  </label>
  <br>

  <label>DESCRIPTION</label>
  <br>

  <textarea type="text" name="sub[description]">


  <input type="submit" value="Create">
</form>

skeddit/app/views/users/index.html.erb
<h1> SKITTLE DEE SKAT</h1>
<h2>HARRY GOT ALL OF DAT</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>

    <% if user.username.include?("harry") %>
      <p>is a champ</p>
    <% else %>
      <p>I'm just an ordinary boy</p>
    <% end %>

  <% end %>
</ul>

<div>The rules of this page are that there are no rules #BradPitt</div>

skeddit/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

  <form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
    <label>Username
      <input type="text" name="user[username]">
    </label>

    <label>Password
      <input type="password" name="user[password]"> # remember to set type
    </label>

    <input type="submit" value="Submit"> # remember to set the value
  
  </form>